update the prep branch so I can continue (#42)
* Fab prep - wip (#37)

* wip - lots of incomplete stuff in here

* update uplugin file - support links and fab requirements

* adding filterplugins.ini - may not need this, but it's here in case

* notes on fab requirements/process

* just more noodling

* note for tomorrow's work

* fix: update GitHub Actions to automatically update our uplugin file and create a ScooterUtilsVersion.h file for us.

* fix: forgot I have to have files here to start with.

* Fab prep - wip merge (#38)

* wip - lots of incomplete stuff in here

* update uplugin file - support links and fab requirements

* adding filterplugins.ini - may not need this, but it's here in case

* notes on fab requirements/process

* just more noodling

* note for tomorrow's work

* fix: update GitHub Actions to automatically update our uplugin file and create a ScooterUtilsVersion.h file for us.

* fix: forgot I have to have files here to start with.

* fix: change the workflow name

* fix: more branch name cleanup

* chore(master): release 1.2.4 (#40)

* chore(master): release 1.2.4

* chore: Update version header file

---------

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>

* fix: I fat-fingered a line out of my yml, so may patch number wasn't updating in my c++ version header

* fix: bad json in the uplugin file

* fix: displays the plugin version as a static text string in the editor preferences dialog

* chore(master): release 1.2.5 (#41)

* chore(master): release 1.2.5

* chore: Update version header file

---------

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>

---------

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>

diff --git a/.github/workflows/update-version-header.yml b/.github/workflows/update-version-header.yml
--- a/.github/workflows/update-version-header.yml
+++ b/.github/workflows/update-version-header.yml
@@ -10,10 +10,10 @@ jobs:
     runs-on: ubuntu-latest
     if: ${{ github.event.workflow_run.conclusion == 'success' }}
     steps:
-      - name: Check out the release-please--branches--main branch
+      - name: Check out the release-please--branches--master branch
         uses: actions/checkout@v4
         with:
-          ref: release-please--branches--main
+          ref: release-please--branches--master
       
       
       - name: Update Version Header
@@ -31,21 +31,27 @@ jobs:
           cat Source/ScooterUtils/Public/ScooterUtilsVersion.h
           
 
-          # Update the header file
+          echo # Update the header file
           echo "Updating Source/ScooterUtils/Public/ScooterUtilsVersion.h"
 
-          echo "sed -i 's/#define VERSION_MAJOR [0-9]*/#define VERSION_MAJOR '"$MAJOR"'/' Source/ScooterUtils/Public/ScooterUtilsVersion.h"
-          sed -i 's/#define VERSION_MAJOR [0-9]*/#define VERSION_MAJOR '"$MAJOR"'/' Source/ScooterUtils/Public/ScooterUtilsVersion.h
-          if [ $? -eq 0 ]; then echo "VERSION_MAJOR updated successfully"; else echo "Failed to update VERSION_MAJOR"; fi
+          echo "sed -i 's/#define SCOOTER_UTILS_VERSION_MAJOR [0-9]*/#define SCOOTER_UTILS_VERSION_MAJOR '"$MAJOR"'/' Source/ScooterUtils/Public/ScooterUtilsVersion.h"
+          sed -i 's/#define SCOOTER_UTILS_VERSION_MAJOR [0-9]*/#define SCOOTER_UTILS_VERSION_MAJOR '"$MAJOR"'/' Source/ScooterUtils/Public/ScooterUtilsVersion.h
+          if [ $? -eq 0 ]; then echo "SCOOTER_UTILS_VERSION_MAJOR updated successfully"; else echo "Failed to update SCOOTER_UTILS_VERSION_MAJOR"; fi
           
-          echo "sed -i 's/#define VERSION_MINOR [0-9]*/#define VERSION_MINOR '"$MINOR"'/' Source/ScooterUtils/Public/ScooterUtilsVersion.h"
-          sed -i 's/#define VERSION_MINOR [0-9]*/#define VERSION_MINOR '"$MINOR"'/' Source/ScooterUtils/Public/ScooterUtilsVersion.h
-          if [ $? -eq 0 ]; then echo "VERSION_MINOR updated successfully"; else echo "Failed to update VERSION_MINOR"; fi
+          echo "sed -i 's/#define SCOOTER_UTILS_VERSION_MINOR [0-9]*/#define SCOOTER_UTILS_VERSION_MINOR '"$MINOR"'/' Source/ScooterUtils/Public/ScooterUtilsVersion.h"
+          sed -i 's/#define SCOOTER_UTILS_VERSION_MINOR [0-9]*/#define SCOOTER_UTILS_VERSION_MINOR '"$MINOR"'/' Source/ScooterUtils/Public/ScooterUtilsVersion.h
+          if [ $? -eq 0 ]; then echo "SCOOTER_UTILS_VERSION_MINOR updated successfully"; else echo "Failed to update SCOOTER_UTILS_VERSION_MINOR"; fi
           
-          echo "sed -i 's/#define VERSION_PATCH [0-9]*/#define VERSION_PATCH '"$PATCH"'/' Source/ScooterUtils/Public/ScooterUtilsVersion.h"
-          if [ $? -eq 0 ]; then echo "VERSION_PATCH updated successfully"; else echo "Failed to update VERSION_PATCH"; fi
+          echo "sed -i 's/#define SCOOTER_UTILS_VERSION_PATCH [0-9]*/#define SCOOTER_UTILS_VERSION_PATCH '"$PATCH"'/' Source/ScooterUtils/Public/ScooterUtilsVersion.h"
+          sed -i 's/#define SCOOTER_UTILS_VERSION_PATCH [0-9]*/#define SCOOTER_UTILS_VERSION_PATCH '"$PATCH"'/' Source/ScooterUtils/Public/ScooterUtilsVersion.h
+          if [ $? -eq 0 ]; then echo "SCOOTER_UTILS_VERSION_PATCH updated successfully"; else echo "Failed to update SCOOTER_UTILS_VERSION_PATCH"; fi
 
-          # build a multiplied version number for the uplugin file
+          echo # Print the contents of the header file after updating
+          echo "Contents of Source/ScooterUtils/Public/ScooterUtilsVersion.h after update:"
+          cat Source/ScooterUtils/Public/ScooterUtilsVersion.h
+
+
+          echo # build a multiplied version number for the uplugin file
           MULTIPLIED_VERSION=$((MAJOR * 1000000 + MINOR * 1000 + PATCH))
           echo "Multiplied Version: $MULTIPLIED_VERSION"
 
@@ -58,10 +64,6 @@ jobs:
           if [ $? -eq 0 ]; then echo "uplugin VersionName updated successfully"; else echo "Failed to update upluginVersionName"; fi
        
           
-          # Print the contents of the header file after updating
-          echo "Contents of Source/ScooterUtils/Public/ScooterUtilsVersion.h after update:"
-          cat Source/ScooterUtils/Public/ScooterUtilsVersion.h
-
           echo "Update complete"
 
       
@@ -72,4 +74,4 @@ jobs:
           git add Source/ScooterUtils/Public/ScooterUtilsVersion.h
           git add ScooterUtils.uplugin
           git commit -m "chore: Update version header file"
-          git push origin release-please--branches--main
+          git push origin release-please--branches--master
