fix: displays the plugin version as a static text string in the editor preferences dialog

diff --git a/.github/workflows/update-version-header.yml b/.github/workflows/update-version-header.yml
--- a/.github/workflows/update-version-header.yml
+++ b/.github/workflows/update-version-header.yml
@@ -34,17 +34,17 @@ jobs:
           echo # Update the header file
           echo "Updating Source/ScooterUtils/Public/ScooterUtilsVersion.h"
 
-          echo "sed -i 's/#define VERSION_MAJOR [0-9]*/#define VERSION_MAJOR '"$MAJOR"'/' Source/ScooterUtils/Public/ScooterUtilsVersion.h"
-          sed -i 's/#define VERSION_MAJOR [0-9]*/#define VERSION_MAJOR '"$MAJOR"'/' Source/ScooterUtils/Public/ScooterUtilsVersion.h
-          if [ $? -eq 0 ]; then echo "VERSION_MAJOR updated successfully"; else echo "Failed to update VERSION_MAJOR"; fi
+          echo "sed -i 's/#define SCOOTER_UTILS_VERSION_MAJOR [0-9]*/#define SCOOTER_UTILS_VERSION_MAJOR '"$MAJOR"'/' Source/ScooterUtils/Public/ScooterUtilsVersion.h"
+          sed -i 's/#define SCOOTER_UTILS_VERSION_MAJOR [0-9]*/#define SCOOTER_UTILS_VERSION_MAJOR '"$MAJOR"'/' Source/ScooterUtils/Public/ScooterUtilsVersion.h
+          if [ $? -eq 0 ]; then echo "SCOOTER_UTILS_VERSION_MAJOR updated successfully"; else echo "Failed to update SCOOTER_UTILS_VERSION_MAJOR"; fi
           
-          echo "sed -i 's/#define VERSION_MINOR [0-9]*/#define VERSION_MINOR '"$MINOR"'/' Source/ScooterUtils/Public/ScooterUtilsVersion.h"
-          sed -i 's/#define VERSION_MINOR [0-9]*/#define VERSION_MINOR '"$MINOR"'/' Source/ScooterUtils/Public/ScooterUtilsVersion.h
-          if [ $? -eq 0 ]; then echo "VERSION_MINOR updated successfully"; else echo "Failed to update VERSION_MINOR"; fi
+          echo "sed -i 's/#define SCOOTER_UTILS_VERSION_MINOR [0-9]*/#define SCOOTER_UTILS_VERSION_MINOR '"$MINOR"'/' Source/ScooterUtils/Public/ScooterUtilsVersion.h"
+          sed -i 's/#define SCOOTER_UTILS_VERSION_MINOR [0-9]*/#define SCOOTER_UTILS_VERSION_MINOR '"$MINOR"'/' Source/ScooterUtils/Public/ScooterUtilsVersion.h
+          if [ $? -eq 0 ]; then echo "SCOOTER_UTILS_VERSION_MINOR updated successfully"; else echo "Failed to update SCOOTER_UTILS_VERSION_MINOR"; fi
           
-          echo "sed -i 's/#define VERSION_PATCH [0-9]*/#define VERSION_PATCH '"$PATCH"'/' Source/ScooterUtils/Public/ScooterUtilsVersion.h"
-          sed -i 's/#define VERSION_PATCH [0-9]*/#define VERSION_PATCH '"$PATCH"'/' Source/ScooterUtils/Public/ScooterUtilsVersion.h
-          if [ $? -eq 0 ]; then echo "VERSION_PATCH updated successfully"; else echo "Failed to update VERSION_PATCH"; fi
+          echo "sed -i 's/#define SCOOTER_UTILS_VERSION_PATCH [0-9]*/#define SCOOTER_UTILS_VERSION_PATCH '"$PATCH"'/' Source/ScooterUtils/Public/ScooterUtilsVersion.h"
+          sed -i 's/#define SCOOTER_UTILS_VERSION_PATCH [0-9]*/#define SCOOTER_UTILS_VERSION_PATCH '"$PATCH"'/' Source/ScooterUtils/Public/ScooterUtilsVersion.h
+          if [ $? -eq 0 ]; then echo "SCOOTER_UTILS_VERSION_PATCH updated successfully"; else echo "Failed to update SCOOTER_UTILS_VERSION_PATCH"; fi
 
           echo # Print the contents of the header file after updating
           echo "Contents of Source/ScooterUtils/Public/ScooterUtilsVersion.h after update:"
